export type ChallengeLevel = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
export type ChallengeType = "translate" | "definition" | "fill_blank" | "grammar" | "choose" | "reverse_translate" | "idiom";

export interface Challenge {
  type: ChallengeType;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  word?: string;
  level: ChallengeLevel;
}

const CHALLENGES: Challenge[] = [
  // ══════════════════════════════ A1 ══════════════════════════════
  { level:"A1", type:"translate", word:"King",
    question:"What does 'King' mean in Russian?",
    options:["Ферзь","Король","Слон","Пешка"], correct:1,
    explanation:"King = Король. The most important piece — protect it at all costs!" },
  { level:"A1", type:"translate", word:"Queen",
    question:"What does 'Queen' mean?",
    options:["Ладья","Пешка","Ферзь","Конь"], correct:2,
    explanation:"Queen = Ферзь. The most powerful piece on the board." },
  { level:"A1", type:"translate", word:"Pawn",
    question:"What does 'Pawn' mean?",
    options:["Конь","Слон","Ладья","Пешка"], correct:3,
    explanation:"Pawn = Пешка. The smallest but can promote to queen!" },
  { level:"A1", type:"translate", word:"Rook",
    question:"What does 'Rook' mean?",
    options:["Ладья","Слон","Ферзь","Король"], correct:0,
    explanation:"Rook = Ладья. Moves horizontally and vertically." },
  { level:"A1", type:"translate", word:"Bishop",
    question:"What does 'Bishop' mean?",
    options:["Конь","Слон","Пешка","Ладья"], correct:1,
    explanation:"Bishop = Слон. Moves diagonally across the board." },
  { level:"A1", type:"translate", word:"Knight",
    question:"What does 'Knight' mean?",
    options:["Ладья","Слон","Ферзь","Конь"], correct:3,
    explanation:"Knight = Конь. The only piece that can jump over others!" },
  { level:"A1", type:"translate", word:"Move",
    question:"What does 'Move' mean?",
    options:["Удар","Ход","Правило","Победа"], correct:1,
    explanation:"Move = Ход. You make one move per turn in chess." },
  { level:"A1", type:"translate", word:"Win",
    question:"What does 'Win' mean?",
    options:["Проиграть","Ничья","Выиграть","Начать"], correct:2,
    explanation:"Win = Выиграть / Победа." },
  { level:"A1", type:"translate", word:"Lose",
    question:"What does 'Lose' mean?",
    options:["Выиграть","Проиграть","Защищать","Атаковать"], correct:1,
    explanation:"Lose = Проиграть. Nobody likes to lose, but it helps you improve!" },
  { level:"A1", type:"translate", word:"Draw",
    question:"In chess 'Draw' means…",
    options:["Победа","Ничья","Поражение","Жертва"], correct:1,
    explanation:"Draw = Ничья. Both players share the point." },
  { level:"A1", type:"choose", word:"Attack",
    question:"What does 'Attack' mean?",
    options:["Защищать","Нападать","Отступать","Ждать"], correct:1,
    explanation:"Attack = Нападать / Атаковать." },
  { level:"A1", type:"choose", word:"Defend",
    question:"What does 'Defend' mean?",
    options:["Атаковать","Защищать","Жертвовать","Рокировать"], correct:1,
    explanation:"Defend = Защищать. Always defend your king!" },
  { level:"A1", type:"fill_blank",
    question:"The king is in _____ — it is under attack!",
    options:["stalemate","check","draw","promotion"], correct:1,
    explanation:"Check = Шах. Your king is attacked and must escape!" },
  { level:"A1", type:"fill_blank",
    question:"White pieces always move _____.",
    options:["last","second","first","never"], correct:2,
    explanation:"White always moves first in chess — that's the rule!" },
  { level:"A1", type:"choose",
    question:"How many squares does a chessboard have?",
    options:["32","48","64","72"], correct:2,
    explanation:"A chessboard has 8×8 = 64 squares." },

  // ══════════════════════════════ A2 ══════════════════════════════
  { level:"A2", type:"translate", word:"Castle",
    question:"In chess, to 'Castle' means…",
    options:["Жертвовать ферзя","Рокировать","Взять пешку","Объявить мат"], correct:1,
    explanation:"Castle = Рокировать. Moving the king two squares toward a rook for safety." },
  { level:"A2", type:"translate", word:"Capture",
    question:"What does 'Capture' mean?",
    options:["Защитить","Взять / Съесть фигуру","Отступить","Поставить мат"], correct:1,
    explanation:"Capture = Взять фигуру. You remove the opponent's piece from the board." },
  { level:"A2", type:"translate", word:"Strategy",
    question:"What does 'Strategy' mean?",
    options:["Удача","Тактика","Стратегия","Правило"], correct:2,
    explanation:"Strategy = Стратегия. Long-term planning in chess." },
  { level:"A2", type:"translate", word:"Sacrifice",
    question:"What does 'Sacrifice' mean in chess?",
    options:["Рокировка","Жертва","Атака","Защита"], correct:1,
    explanation:"Sacrifice = Жертва. Giving up material to gain a positional or tactical advantage." },
  { level:"A2", type:"fill_blank",
    question:"The queen is the most _____ piece on the board.",
    options:["slow","useless","powerful","small"], correct:2,
    explanation:"Powerful = Мощный. The queen can move in any direction any number of squares." },
  { level:"A2", type:"fill_blank",
    question:"You should _____ your pieces to the center early in the game.",
    options:["hide","develop","remove","ignore"], correct:1,
    explanation:"Develop = Развивать. Bring your pieces out where they are most active." },
  { level:"A2", type:"grammar",
    question:"Choose the correct sentence:",
    options:["I winning this game.","I am winning this game.","I is winning this game.","I wins this game."],
    correct:1, explanation:"'I am + verb-ing' = Present Continuous for actions happening right now." },
  { level:"A2", type:"choose",
    question:"What does 'opponent' mean?",
    options:["Партнёр","Соперник","Тренер","Зритель"], correct:1,
    explanation:"Opponent = Соперник. The person you are playing against." },
  { level:"A2", type:"choose",
    question:"'Aggressive' play style means…",
    options:["Playing slowly and carefully","Avoiding all captures","Attacking boldly and often","Resigning early"], correct:2,
    explanation:"Aggressive = Агрессивный. Always looking to attack the opponent." },
  { level:"A2", type:"translate", word:"Opening",
    question:"What is the 'Opening' in chess?",
    options:["Эндшпиль","Дебют","Миттельшпиль","Гамбит"], correct:1,
    explanation:"Opening = Дебют. The first phase of the game when pieces are developed." },
  { level:"A2", type:"fill_blank",
    question:"Chess is a game of skill and _____.",
    options:["luck","noise","strategy","speed"], correct:2,
    explanation:"Strategy = Стратегия. Chess requires strategic thinking, not luck." },
  { level:"A2", type:"choose",
    question:"Which word means 'to improve'?",
    options:["Worsen","Get better","Give up","Forget"], correct:1,
    explanation:"Improve = Улучшиться. Practice helps you improve your chess!" },
  { level:"A2", type:"choose",
    question:"'Beginner' means…",
    options:["Эксперт","Новичок","Победитель","Тренер"], correct:1,
    explanation:"Beginner = Новичок. Everyone starts as a beginner!" },

  // ══════════════════════════════ B1 ══════════════════════════════
  { level:"B1", type:"translate", word:"Stalemate",
    question:"What is a 'Stalemate'?",
    options:["Шах","Мат","Пат","Ничья по соглашению"], correct:2,
    explanation:"Stalemate = Пат. The player has no legal moves but is NOT in check — it's a draw!" },
  { level:"B1", type:"translate", word:"Endgame",
    question:"What is the 'Endgame'?",
    options:["Дебют","Миттельшпиль","Эндшпиль","Гамбит"], correct:2,
    explanation:"Endgame = Эндшпиль. The final phase when few pieces remain." },
  { level:"B1", type:"definition", word:"Fork",
    question:"What is a 'Fork' in chess?",
    options:["A draw offer","Attacking two pieces simultaneously","Protecting the king","A type of opening"], correct:1,
    explanation:"Fork = Вилка. One piece attacks two opponent pieces at the same time — very powerful!" },
  { level:"B1", type:"definition", word:"Pin",
    question:"What is a 'Pin' in chess?",
    options:["Moving the king to safety","A piece that cannot move without exposing a more valuable piece","Trading equal pieces","Blocking a pawn"], correct:1,
    explanation:"Pin = Связка. A pinned piece shields a more valuable piece behind it." },
  { level:"B1", type:"definition", word:"Blunder",
    question:"What is a 'Blunder'?",
    options:["An excellent move","A planned sacrifice","A very serious mistake","A defensive move"], correct:2,
    explanation:"Blunder = Грубая ошибка. A move that seriously worsens your position, often losing material." },
  { level:"B1", type:"fill_blank",
    question:"After the _____, both players developed their pieces.",
    options:["endgame","blunder","opening","checkmate"], correct:2,
    explanation:"Opening = Дебют. The first moves are called the 'opening'." },
  { level:"B1", type:"fill_blank",
    question:"The pawn can be _____ into a queen when it reaches the last rank.",
    options:["turned","promoted","deleted","destroyed"], correct:1,
    explanation:"Promoted = Превращён. Pawn promotion is one of chess's most exciting moments!" },
  { level:"B1", type:"grammar",
    question:"Which sentence is correct?",
    options:["She has been play chess for 10 years.","She has been playing chess for 10 years.","She have been playing chess for 10 years.","She is been playing chess for 10 years."],
    correct:1, explanation:"'Has been + verb-ing' = Present Perfect Continuous for an ongoing action." },
  { level:"B1", type:"choose",
    question:"'Outplay' means…",
    options:["Play a draw","Play worse","Play better and beat the opponent","Abandon the game"], correct:2,
    explanation:"Outplay = Переиграть. To play more skillfully than your opponent." },
  { level:"B1", type:"translate", word:"Gambit",
    question:"What is a 'Gambit'?",
    options:["Защитный ход","Жертва пешки/фигуры ради инициативы","Рокировка","Пат"], correct:1,
    explanation:"Gambit = Гамбит. Sacrificing material (usually a pawn) early for faster development or initiative." },
  { level:"B1", type:"idiom",
    question:"'The ball is in your court' means…",
    options:["Play tennis instead","It's your turn to decide or act","The game is over","Someone made a mistake"], correct:1,
    explanation:"This English idiom means it's your responsibility to make the next move — just like in chess!" },
  { level:"B1", type:"fill_blank",
    question:"A good chess player always _____ the consequences of each move.",
    options:["ignores","avoids","considers","forgets"], correct:2,
    explanation:"Considers = Учитывает/Обдумывает. Always think before you move!" },
  { level:"B1", type:"choose",
    question:"'Momentum' in a game means…",
    options:["Потеря темпа","Инициатива и преимущество","Конец игры","Защитная позиция"], correct:1,
    explanation:"Momentum = Инициатива / Momentum. When you have the momentum you control the game." },
  { level:"B1", type:"definition", word:"Skewer",
    question:"What is a 'Skewer'?",
    options:["A type of promotion","An attack on a valuable piece that reveals a piece behind it","A defensive formation","A drawing technique"], correct:1,
    explanation:"Skewer = Рентген / Просвечивание. Like a pin in reverse — the valuable piece must move, exposing the piece behind." },

  // ══════════════════════════════ B2 ══════════════════════════════
  { level:"B2", type:"translate", word:"Zugzwang",
    question:"What does 'Zugzwang' mean?",
    options:["Гамбит","Вилка","Цугцванг — вынужденный ход во вред себе","Связка"], correct:2,
    explanation:"Zugzwang = Цугцванг. A situation where any move a player makes worsens their position." },
  { level:"B2", type:"definition", word:"Prophylaxis",
    question:"What is 'Prophylaxis' in chess?",
    options:["An aggressive attack","Preventing opponent's plans before they happen","A type of endgame","A pawn structure"], correct:1,
    explanation:"Prophylaxis = Профилактика. Anticipating and stopping your opponent's ideas before they execute them." },
  { level:"B2", type:"grammar",
    question:"He _____ the match if he had not blundered.",
    options:["would won","would have won","will have won","would wins"], correct:1,
    explanation:"Third conditional: 'would have + past participle' for unreal past situations." },
  { level:"B2", type:"fill_blank",
    question:"The position is _____ — neither side can improve their position.",
    options:["decisive","active","dynamic","static"], correct:3,
    explanation:"Static = Статичная. A static position has no immediate tactics; strategy is key." },
  { level:"B2", type:"choose",
    question:"'Decisive advantage' means…",
    options:["A small edge","Equal position","A winning advantage","A losing position"], correct:2,
    explanation:"Decisive = Решающий. A decisive advantage almost guarantees victory with correct play." },
  { level:"B2", type:"idiom",
    question:"'Keep your cards close to your chest' means…",
    options:["Play aggressively","Protect your king","Keep your plans secret","Trade pieces equally"], correct:2,
    explanation:"This idiom means to not reveal your intentions — crucial in chess when hiding your strategy!" },
  { level:"B2", type:"definition", word:"Compensation",
    question:"'Compensation' in chess means…",
    options:["Losing material deliberately","Benefits (activity/initiative) that offset material deficit","A type of draw","Defending passively"], correct:1,
    explanation:"Compensation = Компенсация. When you sacrifice material but gain positional or tactical benefits in return." },
  { level:"B2", type:"fill_blank",
    question:"The bishop pair is a long-term _____ that becomes stronger in open positions.",
    options:["weakness","blunder","advantage","mistake"], correct:2,
    explanation:"Advantage = Преимущество. Two bishops together often outperform two knights in open positions." },
  { level:"B2", type:"grammar",
    question:"By the time she resigned, her opponent _____ the queen for three moves.",
    options:["had been threatening","was threatening","has threatened","threatens"], correct:0,
    explanation:"Past Perfect Continuous: 'had been + verb-ing' for an action ongoing before another past event." },
  { level:"B2", type:"translate", word:"Middlegame",
    question:"What is the 'Middlegame'?",
    options:["Дебют","Эндшпиль","Миттельшпиль","Гамбит"], correct:2,
    explanation:"Middlegame = Миттельшпиль. The phase between opening and endgame — where most tactics happen." },
  { level:"B2", type:"choose",
    question:"'Tempo' in chess refers to…",
    options:["Speed of the clock","A turn or move unit; gaining time in development","The board size","Piece value"], correct:1,
    explanation:"Tempo = Темп. Gaining a tempo means achieving your goals in fewer moves than the opponent." },
  { level:"B2", type:"definition", word:"Overloaded piece",
    question:"An 'Overloaded piece' is one that…",
    options:["Has too much value","Is defending two or more things simultaneously and cannot do both","Has been captured","Cannot move legally"], correct:1,
    explanation:"Overloaded = Перегруженная фигура. A piece defending two threats at once — exploit it!" },

  // ══════════════════════════════ C1 ══════════════════════════════
  { level:"C1", type:"definition", word:"Triangulation",
    question:"'Triangulation' is a technique used to…",
    options:["Attack three pawns","Waste a tempo with the king to achieve zugzwang","Promote a pawn","Build a fortress"], correct:1,
    explanation:"Triangulation = Треугольник. The king moves in a triangle to lose a tempo and force zugzwang on the opponent." },
  { level:"C1", type:"grammar",
    question:"Which sentence uses the subjunctive mood correctly?",
    options:["If the rook was active, White wins easily.","It is essential that every piece be developed efficiently.","Had the queen moved, Black would win the game.","The position looks as if it was completely lost."],
    correct:1, explanation:"The subjunctive 'be' (not 'is') is used after 'essential that', 'important that', etc." },
  { level:"C1", type:"idiom",
    question:"'The writing is on the wall' means…",
    options:["Notes are important","The outcome (usually bad) is already clear and inevitable","Start writing your moves","The game will be drawn"], correct:1,
    explanation:"This idiom means the bad outcome is obvious and unavoidable — like a completely lost chess position!" },
  { level:"C1", type:"fill_blank",
    question:"The knight _____ to an outpost on d5, from where it dominates the entire board.",
    options:["maneuvered","blundered","retreated","sacrificed"], correct:0,
    explanation:"Maneuvered = Совершил манёвр. A maneuver is a sequence of moves to improve a piece's position." },
  { level:"C1", type:"choose",
    question:"'Nuance' in the context of chess analysis means…",
    options:["A big tactical blow","A subtle distinction or refinement that affects the evaluation","A type of opening","A blunder"], correct:1,
    explanation:"Nuance = Нюанс. Small differences in position that only experienced players notice." },
  { level:"C1", type:"definition", word:"Zugzwang vs Stalemate",
    question:"What distinguishes Zugzwang from Stalemate?",
    options:["They are identical concepts","In Zugzwang the player IS in check; in Stalemate they are not","In Zugzwang the player has moves but all worsen the position; Stalemate means NO legal moves","Stalemate is a loss; Zugzwang is a win"], correct:2,
    explanation:"Key distinction: Zugzwang = moves exist but all hurt you. Stalemate = no legal moves at all (draw)." },
  { level:"C1", type:"grammar",
    question:"Choose the most precise academic phrasing:",
    options:["Chess requires players think strategically.","Chess requires players to think strategically.","Chess requires players thinking strategically.","Chess requires players thought strategically."],
    correct:1, explanation:"'Require + object + to infinitive' is the correct formal structure: 'requires players to think'." },
  { level:"C1", type:"idiom",
    question:"'To have the upper hand' means…",
    options:["To play with white pieces","To be in a position of advantage","To sacrifice a piece","To offer a draw"], correct:1,
    explanation:"Upper hand = Преимущество / Превосходство. Having the upper hand means you're in control." },
  { level:"C1", type:"fill_blank",
    question:"The _____ of the position determines whether aggressive or defensive play is appropriate.",
    options:["color","nature","name","age"], correct:1,
    explanation:"Nature = Характер/Природа. The nature (characteristics) of the position dictates the correct plan." },
  { level:"C1", type:"choose",
    question:"'Counterintuitive' means…",
    options:["Easy to understand","Against what one would naturally expect","Very complex","Mathematically precise"], correct:1,
    explanation:"Counterintuitive = Контринтуитивный. Many brilliant chess moves are counterintuitive — they look wrong but are best!" },

  // ══════════════════════════════ C2 ══════════════════════════════
  { level:"C2", type:"idiom",
    question:"'Pyrrhic victory' refers to…",
    options:["A quick win","A victory won at such great cost it is tantamount to defeat","Winning with pawns only","A draw by repetition"], correct:1,
    explanation:"Pyrrhic victory = Пиррова победа. Winning but losing so much in the process it barely matters." },
  { level:"C2", type:"grammar",
    question:"Which expresses the highest degree of certainty about the past?",
    options:["He might have resigned earlier.","He could have resigned earlier.","He must have resigned due to time pressure.","He should have resigned earlier."], correct:2,
    explanation:"'Must have + past participle' = logical certainty about a past event (near 100% confident)." },
  { level:"C2", type:"definition", word:"Lucena position",
    question:"The 'Lucena position' is…",
    options:["A famous checkmate pattern","A key winning rook endgame technique","A specific opening variation","A type of fortress defense"], correct:1,
    explanation:"Lucena position = Позиция Луцены. A fundamental rook-and-pawn vs rook endgame that demonstrates the 'bridge building' technique." },
  { level:"C2", type:"fill_blank",
    question:"The grandmaster's _____ of the position revealed layers of complexity invisible to weaker players.",
    options:["dismissal","mishandling","elucidation","avoidance"], correct:2,
    explanation:"Elucidation = Прояснение/Разъяснение. To elucidate means to make something clear and understandable." },
  { level:"C2", type:"choose",
    question:"'Perspicacious' most closely means…",
    options:["Reckless","Having a ready insight into things; shrewd","Overly cautious","Verbose"], correct:1,
    explanation:"Perspicacious = Проницательный. A perspicacious player sees deeply into positions that others miss." },
  { level:"C2", type:"idiom",
    question:"'Caught between Scylla and Charybdis' means…",
    options:["Playing near the edge of the board","Facing two equally dangerous threats with no good escape","Having two winning moves","Being in stalemate"], correct:1,
    explanation:"This classical idiom = caught between two equally bad options — exactly like a losing chess position!" },
  { level:"C2", type:"grammar",
    question:"Select the sentence with correct use of inversion for emphasis:",
    options:["Never I have seen such a brilliant combination.","Never have I seen such a brilliant combination.","I never have seen such a brilliant combination.","Never seen have I such a brilliant combination."],
    correct:1, explanation:"Inversion after negative adverbs: 'Never have I seen…' — subject and auxiliary are inverted." },
  { level:"C2", type:"definition", word:"Retrograde analysis",
    question:"'Retrograde analysis' in chess problems means…",
    options:["Analyzing future moves","Working backwards from a position to determine what moves must have occurred","A type of endgame study","Playing chess in reverse"], correct:1,
    explanation:"Retrograde analysis = Ретроградный анализ. Deducing the history of a position by working backwards — chess detective work!" },
  { level:"C2", type:"fill_blank",
    question:"The position's _____ nature makes it resistant to simplification despite White's material advantage.",
    options:["mundane","labyrinthine","trivial","binary"], correct:1,
    explanation:"Labyrinthine = Лабиринтообразный. Extremely complex, with many intertwined variations — like a labyrinth." },
  { level:"C2", type:"choose",
    question:"'Dialectical' thinking in chess refers to…",
    options:["Speaking during the game","Considering opposing forces and how they interact to reach a synthesis","Calculating only one line","Playing randomly"], correct:1,
    explanation:"Dialectical = Диалектический. Understanding how competing forces (attack/defense, space/pieces) interact — advanced chess philosophy." },
];

// Track used questions per session to avoid repetition
const usedIndices = new Set<number>();

export function getRandomChallenge(level: ChallengeLevel): Challenge {
  const pool = CHALLENGES.filter(c => c.level === level);
  if (pool.length === 0) return CHALLENGES[0];

  // Filter out recently used ones
  const unused = pool.filter(c => !usedIndices.has(CHALLENGES.indexOf(c)));
  const source = unused.length > 0 ? unused : pool; // reset if all used

  const idx = Math.floor(Math.random() * source.length);
  const challenge = source[idx];
  const globalIdx = CHALLENGES.indexOf(challenge);
  usedIndices.add(globalIdx);

  // Keep set manageable
  if (usedIndices.size > 30) {
    const first = usedIndices.values().next().value as number;
    usedIndices.delete(first);
  }

  return challenge;
}

export function getChallengesForDifficultyRange(min: ChallengeLevel, max: ChallengeLevel): Challenge[] {
  const ORDER: ChallengeLevel[] = ["A1","A2","B1","B2","C1","C2"];
  const minI = ORDER.indexOf(min), maxI = ORDER.indexOf(max);
  return CHALLENGES.filter(c => ORDER.indexOf(c.level) >= minI && ORDER.indexOf(c.level) <= maxI);
}

export const LEVEL_DESCRIPTIONS: Record<ChallengeLevel, string> = {
  A1: "Complete beginner — basic chess vocabulary",
  A2: "Elementary — common chess terms & phrases",
  B1: "Intermediate — tactics vocabulary & grammar",
  B2: "Upper-intermediate — complex ideas & idioms",
  C1: "Advanced — academic language & nuance",
  C2: "Mastery — sophisticated expressions & analysis",
};
